project_id = "icwidsqbydgycuedhznc"
[functions.notify-admins-on-feedback]
enabled = true
verify_jwt = true
import_map = "./functions/notify-admins-on-feedback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-admins-on-feedback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-admins-on-feedback/*.html" ]
